(*
  The contents of this file define the grammar of the Zircon programming language,
  in the Extended Backus-Naur Form* defined in ISO/IEC 14977:1996, accessible through:
    https://www.cl.cam.ac.uk/~mgk25/iso-14977.pdf

  *: The EBNF form defines `´` as a character used to define the start of a string.
     Instead, I am using `'` (it's easier to type)
*)


